<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/"
    xmlns:referrer="http://a9.com/-/opensearch/extensions/referrer/1.0/"
    xmlns:suggestions="http://www.opensearch.org/specifications/opensearch/extensions/suggestions/1.1"
    xmlns:err="http://jelix.org/ns/xmlerror/1.0"
	xml:lang="{$lang}">
  <ShortName>{$opensearch->shortName|escxml}</ShortName>
  <Description>{$opensearch->description|escxml}</Description>
  {if $opensearch->tags}<Tags>{$opensearch->tags|escxml}</Tags>{/if}
  {if $opensearch->contact}<Contact>{$opensearch->contact|escxml}</Contact>{/if}
  {foreach $urls as $url}
    <Url type="{$url->type|escxml}" indexOffset="{$url->indexOffset|escxml}" pageOffset="{$url->pageOffset|escxml}" rel="{$url->rel|escxml}" template="{$url->template|escxml}" />
  {/foreach}
  {if $opensearch->longName}<LongName>{$opensearch->longName|escxml}</LongName>{/if}
  {if $opensearch->imageLink}<Image height="{$opensearch->imageHeight|escxml}" width="{$opensearch->imageWidth|escxml}" type="{$opensearch->imageType|escxml}">{$opensearch->imageLink|escxml}</Image>{/if}
  {if $opensearch->iconLink}<Image height="{$opensearch->iconHeight|escxml}" width="{$opensearch->iconWidth|escxml}" type="{$opensearch->iconType|escxml}">{$opensearch->iconLink|escxml}</Image>{/if}
  {if $opensearch->exemple}<Query role="example" searchTerms="{$opensearch->exmple|escxml}" />{/if}
  {if $opensearch->developer}<Developer>{$opensearch->developer|escxml}</Developer>{/if}
  {if $opensearch->attribution}<Attribution>{$opensearch->attribution|escxml}</Attribution>{/if}
  {if $opensearch->syndicationRight}<SyndicationRight>{$opensearch->syndicationRight|escxml}</SyndicationRight>{/if}
  {if $opensearch->adultContent}<AdultContent>{$opensearch->adultContent|escxml}</AdultContent>{/if}
  {foreach $opensearch->languages as $language}
    <Language>{$language|escxml}</Language>
  {/foreach}
  {foreach $opensearch->outputEncodings as $outputEncoding}
    <OutputEncoding>{$outputEncoding|escxml}</OutputEncoding>
  {/foreach}
  {foreach $opensearch->inputEncodings as $inputEncoding}
  <InputEncoding>{$inputEncoding|escxml}</InputEncoding>
  {/foreach}
{* endtag is generated by the response *}
